import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import test from 'node:test'

test('AI buyer show workflow is exposed as an independent app view', async () => {
  const appSource = await readFile(new URL('../App.vue', import.meta.url), 'utf8')

  assert.match(appSource, /import BuyerShowWorkflow from '\.\/views\/BuyerShowWorkflow\.vue'/)
  assert.match(appSource, /currentView === 'buyer_show_workflow'/)
  assert.match(appSource, /id: 'ai_workflows'[\s\S]*label: 'AI 工作流'[\s\S]*children: \[/)
  assert.match(appSource, /\{ id: 'ai_video', icon: '🎞️', label: 'AI 视频工作流' \}/)
  assert.match(appSource, /\{ id: 'buyer_show_workflow', icon: '🛍️', label: 'AI 买家秀工作流' \}/)
  assert.match(appSource, /const expandedNavGroupIds = ref\(new Set\(\['ai_workflows'\]\)\)/)
  assert.match(appSource, /function toggleNavGroup\(item\)/)
  assert.match(appSource, /function isNavGroupActive\(item\)/)
  assert.match(appSource, /class="nav-children"/)
  assert.match(appSource, /<BuyerShowWorkflow\s+v-if="currentView === 'buyer_show_workflow'"/)
})

test('AI buyer show workflow submits the Semir MVP task with stepper controls', async () => {
  const workflowSource = await readFile(new URL('../views/BuyerShowWorkflow.vue', import.meta.url), 'utf8')

  assert.match(workflowSource, /const ADAPTER_ID = 'semir-cloud-drive'/)
  assert.match(workflowSource, /const TASK_ID = 'buyer_show_ai_generate'/)
  assert.match(workflowSource, /import \{ AI_IMAGE_MODELS \} from '\.\.\/utils\/aiImageModels\.js'/)
  assert.match(workflowSource, /<nav class="bsv-stepper" role="tablist"/)
  assert.match(workflowSource, /role="tab"/)
  assert.match(workflowSource, /:aria-selected="activeStep === step\.id"/)
  assert.match(workflowSource, /window\.cs\.runTask\(ADAPTER_ID, TASK_ID, buildRunParams\(\), \{\}\)/)
  assert.match(workflowSource, /const DEFAULT_EXPORT_FOLDER = '~\/Downloads\/AI 买家秀全量测试'/)
  assert.match(workflowSource, /const DEFAULT_MODEL_ID = 'gpt-image-4k'/)
  assert.match(workflowSource, /function toPlainJson\(value, fallback\)/)
  assert.match(workflowSource, />生图模型<\/span>/)
  assert.match(workflowSource, /<select v-model="selectedModelId">/)
  assert.match(workflowSource, /'gemini-3.1-flash-image-preview': 'Gemini Flash'/)
  assert.match(workflowSource, /'gemini-3-pro-image-preview': 'Gemini Pro'/)
  assert.match(workflowSource, /execute_mode: executeMode\.value/)
  assert.match(workflowSource, /flat_cloud_path: flatCloudPath\.value/)
  assert.match(workflowSource, /rows: toPlainJson\(excelPreview\.rows, \[\]\)/)
  assert.match(workflowSource, /headers: toPlainJson\(excelPreview\.headers, \[\]\)/)
  assert.match(workflowSource, /model_id: selectedAiModel\.value\?\.id \|\| DEFAULT_MODEL_ID/)
  assert.match(workflowSource, /model: selectedAiModel\.value\?\.key \|\| 'gpt-image-2'/)
  assert.match(workflowSource, /model_key_tier: selectedAiModel\.value\?\.keyTier \|\| '4k'/)
  assert.match(workflowSource, /image_size: 'source_ratio'/)
  assert.match(workflowSource, /max_generate_jobs: 0/)
  assert.match(workflowSource, /max_model_images_per_row: 500/)
  assert.match(workflowSource, /model_folder_scan_depth: 4/)
  assert.match(workflowSource, /model_folder_scan_max_folders: 500/)
  assert.match(workflowSource, /model_file_info_batch_size: 5/)
  assert.match(workflowSource, /const resumePackageDir = ref\(''\)/)
  assert.match(workflowSource, /<option value="resume">续跑原图包<\/option>/)
  assert.match(workflowSource, /resume_package_dir: isResumeMode\.value \? resumePackageDir\.value : ''/)
  assert.match(workflowSource, /function pickResumePackageDir\(\)/)
  assert.match(workflowSource, /ai_generation_concurrency: 5/)
  assert.match(workflowSource, /ai_result_download_concurrency: 10/)
  assert.doesNotMatch(workflowSource, />生图尺寸</)
  assert.doesNotMatch(workflowSource, />最多真实生图数</)
  assert.doesNotMatch(workflowSource, />单行最多模拍图</)
  assert.doesNotMatch(workflowSource, />1XM 生图并发</)
  assert.doesNotMatch(workflowSource, />AI 结果落图并发</)
  assert.doesNotMatch(workflowSource, /const imageSize = ref/)
  assert.doesNotMatch(workflowSource, /const maxGenerateJobs = ref/)
  assert.doesNotMatch(workflowSource, /const maxModelImagesPerRow = ref/)
  assert.doesNotMatch(workflowSource, /const generationConcurrency = ref/)
  assert.doesNotMatch(workflowSource, /const resultDownloadConcurrency = ref/)
  assert.match(workflowSource, /usage_record_mode: 'ignore'/)
  assert.doesNotMatch(workflowSource, /\/Users\//)
})
